[package]
name = "nezuo/midori"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "shared"

[dependencies]
